### PR TITLE
Added RedHat

### PR DESCRIPTION
**Pull request by pulse-mind**
I added a new task and vers for RedHat

### CODE REVIEW

**Comment by popstas** [comment]
Can you fix tests?

**Comment by pulse-mind** [comment]
Yes I am working on it, sorry, but I am not confident with that

**Comment by pulse-mind** [comment]
done :)

**Comment by pulse-mind** [comment]
But I changed the readme to read on my travis. May be you should not integrate that

**Comment by popstas** [comment]
Thank you, all right, I will revert links in README after merge.

**Comment by popstas** [comment]
@pulse-mind, can you explain mount of `/sys/fs/cgroup:/sys/fs/cgroup:ro`?
I adopting molecule v2 tests, it fails on `create` step when this mount exists and fails on task `Ensure Apache has selected state and enabled on boot` without mounts.

**Comment by pulse-mind** [comment]
Actually I did a copy and paste from others, example : https://github.com/jgeusebroek/ansible-role-maxmind-geoip/blob/master/molecule.yml
But the explanation is here : 
https://www.jeffgeerling.com/blog/2016/how-i-test-ansible-configuration-on-7-different-oses-docker

> One other thing that needs to be configured per-OS is the init system. Because we're dealing with OSes that have a mixture of systemd and sysv init systems, we have to specify in Travis' environment the path to the init system to use, and any extra options that we need to pass to the docker run command to get the image in the right state for Ansible testing. So we'll add two variables for each distribution, init and run_opts:

**Comment by pulse-mind** [comment]
I added that because it was failing on starting a process

**Comment by popstas** [comment]
Ok, thank you

**Pull request merged**
